# Generated by Django 4.0 on 2021-12-30 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('official', '0002_alter_schedule_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='slug',
        ),
    ]
