# Generated by Django 4.0 on 2021-12-31 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('official', '0003_remove_schedule_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='DistrictMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
    ]
