# Generated by Django 4.0 on 2021-12-31 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('official', '0004_districtmap'),
    ]

    operations = [
        migrations.AddField(
            model_name='districtmap',
            name='latitude',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='districtmap',
            name='longitude',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
