# Generated by Django 4.0 on 2021-12-28 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='doctor',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='treatement',
        ),
        migrations.DeleteModel(
            name='Branch',
        ),
        migrations.DeleteModel(
            name='Doctor',
        ),
        migrations.DeleteModel(
            name='Schedule',
        ),
    ]
